### PR TITLE
Method name fixed

### PR DESCRIPTION
**Pull request by MisumiRize**
This PR changes method name from `create` to `build` in accordance with README.md.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by marcelerz** [comment]
Nice find. Thank you! :+1: 
Could you have a look at our CLA? Unfortunately, I can only merge this PR if you agree to the terms.

**Comment by MisumiRize** [comment]
I'd seen the CLA and agreed, but the result doesn't appear.
Should I push one more commit to trigger GitHub hook?
(Is there any other way to notify you of my agreement?)

**Comment by marcelerz** [comment]
I see it now: https://yahoocla.herokuapp.com/-/MisumiRize
Sorry for the delay.

**Comment by MisumiRize** [comment]
Thank you :smile:

**Pull request merged**
